### ISSUE TITLE
what is the advantage of putting the gravity into the state vector?

### ISSUE THREAD

**Issue by canyou2014** [rpng/R-VIO#15]
1. In my mind, the gravity can be calculated by rotation from body to world and [0, 0, 9.8], what is the advantage of putting the gravity into the state vector?
2. I found it converge very slowly, is there any methods for enhancing the convergence rate?

**Comment by huaizheng** [comment]
1. In the world-centric formulation, the gravity in global frame is usually treated as a constant vector [0,0,9.8] because the estimation also runs in the same frame. While, in the robocentric formulation the estimation now runs in a robot (local) frame, and thus the gravity in local frame is not constant which depends on the pose of robot. If you still treat it as a constant vector, i.e., by rotating the constant global gravity to local, the uncertainty in this rotation is ignored. So the first reason to put the gravity into the state vector is to take into account this global-to-local uncertainty. The second reason is that the robocentric formulation has invariant observability properties by adding the gravity into the state vector, which, in addition to the first reason, further improves the estimation consistency. Please refer to our paper for the details.
2. In the code, the gravity vector is treated as a unit vector, because its magnitude is known as 9.8. Also, I re-normalize the updated gravity vector to make sure that its norm is 1. So, there should be no convergence issue about it.
