### ISSUE TITLE
Bias' large fluctuation in R-VIO?

### ISSUE THREAD

**Issue by SimLuo2014** [rpng/R-VIO#17]
Hello! 
I have a question why you put the gravity in the state vector? 
As in most paper, the local gravity can just be calculated from its global counterpart([0,0,9.8]) by a rotation matrix(rotation from world to IMU).
In my experiments, I find the estimated bias in R-VIO have larger fluctuation than their counterparts in ROVIO whose state vector do NOT include the local gravity.
I wonder if the local gravity in R-VIO's state vector is a major factor of the bias' large fluctuation? 
Would you please express some opinions on this issue?

**Comment by huaizheng** [comment]
Thanks @SimLuo2014 for your question.

First of all, R-VIO is developed based on our robocentric VINS formulation which enables it to run without the need to align with the gravitational direction (similar to the visual odometry). This means that the prior knowledge of global gravity (i.e., [0,0,9.8]) is not necessary, because we can use the accelerometer measurement at rest as the initial value of gravity and take into account its uncertainty by jointly estimating the local gravity. This is very important when the prior knowledge is not accurate (e.g., global gravity may not be [0,0,9.8] somewhere) or we try to operate VINS in some unknown environment. As compared with the world-centric VINS or ROVIO which still needs such knowledge of global gravity, our R-VIO is able to navigate only depending on the information from local sensing.

Second, as you have mentioned the estimate of (accelerometer) bias, let us look at the model of accelerometer measurement first: am=a+g+ba+na, where 'a' is the net acceleration, 'g' is the local gravitational acceleration, 'ba' is the sensor bias, and 'na' is the sensor noise. Especially, the world-centric VINS formulated in the fixed global frame of reference obtains 'g' by rotating global gravity to local frame assuming it is perfectly known, while our robocentric VINS formulated in a moving local frame treats 'g' as unknown parameter and jointly estimate it. Thus, there should be some difference between the results of 'g' (and hence, between that of 'ba') from different systems. However, the fluctuation in the R-VIO's estimate of 'ba' does not mean something bad, because 'ba' is modeled as a random walk process which does not ask its estimate to have small fluctuation.

Hope those can help you.
